name: Build LaTeX document

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: congogbv.tex

      - name: Rename file 
        run: mv congogbv.pdf "Sexual violence conflict and female empowerment ${{ steps.date.outputs.date }}.pdf"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Sexual violence conflict and female empowerment ${{ steps.date.outputs.date }}.pdf"
          bodyFile: .github/workflows/release_info.md