name: Build RMarkdown document

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build_rmarkdown:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        uses: addnab/docker-run-action@v3
          with:
              image: koenleuveld/rmarkdown2pdf:0.2
              options: -v ${{ github.workspace }}:/report 
              run: |
                Rscript -e "rmarkdown::render('congogbv.Rmd', output_file = 'congogbv.pdf')"

      - name: Rename file 
        run: mv congogbv.pdf "Sexual violence conflict and female empowerment ${{github.ref_name}}.pdf"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Sexual violence conflict and female empowerment ${{github.ref_name}}.pdf"
          bodyFile: .github/workflows/release_info.md
